---
name: KiCad DRC and ERC Checks

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run KiBot
        uses: INTI-CMNB/KiBot@v2_k8
        with:
          config: kibot.yaml
          schema: xDuinoRails-Thor-M.kicad_sch
          board: xDuinoRails-Thor-M.kicad_pcb

      - name: Cache 3D models
        uses: actions/cache@v4
        with:
          path: 3d_models/
          key: ${{ runner.os }}-kicad-3d-models-${{ hashFiles('**/xDuinoRails-Thor-M.kicad_pcb') }}
      
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: KiCad-Board-Documentation
          path: |
            gen_docs/
            KiCad-Board-Documentation.zip

      - name: Create Release and Upload Asset
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          files: KiCad-Board-Documentation.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

