---
name: KiCad DRC and ERC Checks

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - id: set-matrix
        name: Find KiCad Projects
        run: |
          pro_files=$(find . -maxdepth 1 -name "*.kicad_pro" -exec basename {} .kicad_pro \; | jq -R -s -c 'split("\n") | map(select(length > 0))')
          echo "matrix=${pro_files}" >> $GITHUB_OUTPUT

  check:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        project: ${{ fromJson(needs.setup.outputs.matrix) }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build custom KiBot image
        run: docker build --tag kibot-custom ./.github

      - name: Verify pinion installation
        run: docker run --rm kibot-custom pinion --help

      - name: Run KiBot
        run: >
          docker run --rm
          -v ${{ github.workspace }}:/github/workspace
          -w /github/workspace
          kibot-custom
          kibot
          -c kibot.yaml
          -e ${{ matrix.project }}.kicad_sch
          -b ${{ matrix.project }}.kicad_pcb
          -d assets/${{ matrix.project }}

      - name: Cache 3D models
        uses: actions/cache@v4
        with:
          path: 3d_models/
          key: ${{ runner.os }}-kicad-3d-models-${{ hashFiles(format('**/{0}.kicad_pcb', matrix.project)) }}
          restore-keys: |
            ${{ runner.os }}-kicad-3d-models-

      - name: Upload Documentation Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: KiCad-Docs-${{ matrix.project }}
          path: assets/${{ matrix.project }}/

      - name: Create Release and Upload Asset
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          name: KiCad-Assets-${{ matrix.project }}
          files: assets/${{ matrix.project }}/KiCad-Board-Documentation.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

