---
name: KiCad DRC and ERC Checks

on:
  push:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run KiBot
        uses: INTI-CMNB/KiBot@v2_k8
        with:
          config: kibot.yaml
          schema: xDuinoRails-Thor-M.kicad_sch
          board: xDuinoRails-Thor-M.kicad_pcb

      - name: Cache 3D models
        uses: actions/cache@v4
        with:
          path: 3d_models/
          key: ${{ runner.os }}-kicad-3d-models-${{ hashFiles('**/xDuinoRails-Thor-M.kicad_pcb') }}
      
      - name: Upload Documentation Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: KiCad-Board-Documentation
          # Dieser Pfad muss mit dem 'dir' aus Ihrer kibot.yaml Ã¼bereinstimmen
          path: gen_docs/ 

