---
name: KiCad DRC and ERC Checks

on:
  push:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache 3D models
        uses: actions/cache@v4
        with:
          path: 3d_models/
          key: ${{ runner.os }}-kicad-3d-models-${{ hashFiles('**/xDuinoRails-Thor-M.kicad_pcb') }}

      - name: Commit and Push Documentation
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: Automatische Aktualisierung der KiCad Dokumentation [skip ci]"
          file_pattern: 'gen_docs/**' # Pusht nur Dateien im Dokumentations-Ordner
