---
name: KiCad DRC and ERC Checks

on:
  push:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run KiCad actions
        uses: actions-for-kicad/kicad-actions@v1-k8.0
        with:
          schematic_file_name: xDuinoRails-Thor-M.kicad_sch
          run_erc: true
          pcb_file_name: xDuinoRails-Thor-M.kicad_pcb
          run_drc: true
